### ISSUE TITLE
目前这个扩展仅针对系统一加账号为2.4.0时有效

### ISSUE THREAD

**Issue by neoshui** [kiritoxkiriko/HookOPAccount#1]
目前这个扩展仅针对系统一加账号为2.4.0时有效，当升级系统或是升级一加账号时，登录会失效。

**Comment by kiritoxkiriko** [comment]
升级系统重新刷一遍magisk就行了
氢的一加账号和氧的是不一样的，氧的缺少了国内的登录的插件，所以要用magisk吧氧原来的 覆盖掉

**Comment by neoshui** [comment]
我看了一下magisk模块内的内容，是替换了一加账号这个app，但根据一加app系统版本不同，无法替换成功，我用您的资源在 酷安 发了一个帖子：https://www.coolapk.com/feed/18635268?shareKey=YTYzNDliYWRjNDlhNWViN2E1MjM~&amp;shareUid=1447384&amp;shareFrom=com.coolapk.market_10.1.2&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kiritoxkiriko"<notifications@github.com&gt;; 
发送时间: 2020年5月9日(星期六) 凌晨4:29
收件人: "kiritoxkiriko/HookOPAccount"<HookOPAccount@noreply.github.com&gt;; 
抄送: "税进"<2426726839@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kiritoxkiriko/HookOPAccount] 目前这个扩展仅针对系统一加账号为2.4.0时有效 (#1)





 
升级系统重新刷一遍magisk就行了
 氢的一加账号和氧的是不一样的，氧的缺少了国内的登录的插件，所以要用magisk吧氧原来的 覆盖掉

**Comment by kiritoxkiriko** [comment]
> iritoxkiriko/HookOPAccount"<HookOPAccount@noreply.github.com&gt;; 抄送: "税进"<2426726839@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [kiritoxkiriko/HookOPAccount] 目前这个扩展仅针对系统一加账号为2.4.0时有效 (#1)

是这样的，我用氢os的一加账户替换了系统的，想恢复你再手动把我替换的换成系统自带的再次刷入即可。
我自己只有1+8p，替换的是1+8p的一加账户，不同机型不同版本能不能通用我并不清楚。理论上你可以用自己机型对应的氢版一加账号替换magisk里面的apk再刷入。

**Comment by neoshui** [comment]
> > iritoxkiriko/HookOPAccount"<[HookOPAccount@noreply.github.com](mailto:HookOPAccount@noreply.github.com)>; 抄送: "税进"<[2426726839@qq.com](mailto:2426726839@qq.com)>; "Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [kiritoxkiriko/HookOPAccount] 目前这个扩展仅针对系统一加账号为2.4.0时有效 (#1)
> 
> 是这样的，我用氢os的一加账户替换了系统的，想恢复你再手动把我替换的换成系统自带的再次刷入即可。
> 我自己只有1+8p，替换的是1+8p的一加账户，不同机型不同版本能不能通用我并不清楚。理论上你可以用自己机型对应的氢版一加账号替换magisk里面的apk再刷入。

get
