### ISSUE TITLE
目前2.60版本的无法使用，该怎么降级至2.40

### ISSUE THREAD

**Issue by findyy99** [kiritoxkiriko/HookOPAccount#2]
- 设备是7T，目前系统是印度氧10.3.2，自带一加账号是2.60，卸载后安装apkmirror 的2.40 安装失败，请问有解决办法吗？

- 顺便提一下，我刚刷好系统的时候，安装wallet apk, 直接登录就能用，可以开卡、充值。再登录Google账号，更新软件以后，发现wallet界面一直跳，无法使用了。

**Comment by findyy99** [comment]
目前

> * 设备是7T，目前系统是印度氧10.3.2，自带一加账号是2.60，卸载后安装apkmirror 的2.40 安装失败，请问有解决办法吗？
> * 顺便提一下，我刚刷好系统的时候，安装wallet apk, 直接登录就能用，可以开卡、充值。再登录Google账号，更新软件以后，发现wallet界面一直跳，无法使用了。

### 目前这个搞定了


- 但是可能是有一个新的bug，登录后立马提示登录过期，然后我改了时区才OK（用钱包登录的），但是一进设置点击一加账号就会再次推出提示登录过期。

**Comment by kiritoxkiriko** [comment]
可能是不同机型使用的一加账号版本不一样，可以自己对应提取氢的apk再刷入。
