### ISSUE TITLE
一加8pro无法使用pay

### ISSUE THREAD

**Issue by crazyng6** [kiritoxkiriko/HookOPAccount#3]
一加8pro，氧os10.5.8，无法使用pay功能，最后一步设置支付密码的时候提示钱包版本过低，- 但是钱包app已在商店更新到最新版了。

**Comment by xayane** [comment]
> 一加8pro，氧os10.5.8，无法使用pay功能，最后一步设置支付密码的时候提示钱包版本过低，- 但是钱包app已在商店更新到最新版了。

请问你解决没有，我也遇到相同的问题。。。

**Comment by xayane** [comment]
> 一加8pro，氧os10.5.8，无法使用pay功能，最后一步设置支付密码的时候提示钱包版本过低，- 但是钱包app已在商店更新到最新版了。

我是一加8，氧10.5.9，提示钱包版本过低。。。目前安装的是3.4.1版本。

**Comment by crazyng6** [comment]
> > 一加8pro，氧os10.5.8，无法使用pay功能，最后一步设置支付密码的时候提示钱包版本过低，- 但是钱包app已在商店更新到最新版了。
> 
> 
> 
> 我是一加8，氧10.5.9，提示钱包版本过低。。。目前安装的是3.4.1版本。

没有解决呢，已经放弃了。。。
